import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Bismillah Risbang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-dvh p-6 min-w-dvW flex justify-center items-center"
      >
        {children}
      </body>
    </html>
  );
}
